{{- if .Values.namespaceCreate }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- include "tapsi-food-map.labels" . | nindent 4 }}
    app.kubernetes.io/component: namespace
{{- end }}