{{- if .Values.app.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "tapsi-food-map.fullname" . }}-pdb
  labels:
    {{- include "tapsi-food-map.labels" . | nindent 4 }}
    app.kubernetes.io/component: disruption-budget
spec:
  {{- if .Values.app.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.app.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.app.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.app.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tapsi-food-map.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: application
{{- end }}