apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tapsi-food-map.fullname" . }}-secrets
  labels:
    {{- include "tapsi-food-map.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
type: Opaque
data:
  secretKey: {{ .Values.secrets.secretKey | b64enc | quote }}
  dbPassword: {{ .Values.secrets.dbPassword | b64enc | quote }}
  metabaseUsername: {{ .Values.secrets.metabaseUsername | b64enc | quote }}
  metabasePassword: {{ .Values.secrets.metabasePassword | b64enc | quote }}
  {{- if .Values.secrets.redisPassword }}
  redisPassword: {{ .Values.secrets.redisPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.grafanaAdminPassword }}
  grafanaAdminPassword: {{ .Values.secrets.grafanaAdminPassword | b64enc | quote }}
  {{- end }}

---
{{- if and .Values.monitoringIngress.enabled .Values.monitoring.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-basic-auth
  labels:
    {{- include "tapsi-food-map.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring-auth
type: Opaque
data:
  # Default: admin / monitoring (change in production)
  # Generated with: htpasswd -nb admin monitoring | base64
  auth: {{ "admin:$apr1$ePPgIfEz$.L7/DQvA9Yqu8DgyP/" | b64enc | quote }}
{{- end }}