# Chart.yaml - Helm chart metadata for Tapsi Food Map Dashboard
apiVersion: v2
name: tapsi-food-map
description: A Helm chart for Tapsi Food Map Dashboard - Production-ready Flask application with PostgreSQL, Redis, and monitoring
type: application
version: 2.0.0
appVersion: "2.0.0"
home: https://github.com/tapsi/food-map-dashboard
sources:
  - https://github.com/tapsi/food-map-dashboard
maintainers:
  - name: Tapsi Engineering Team
    email: engineering@tapsi.ir
keywords:
  - flask
  - food-delivery
  - mapping
  - analytics
  - dashboard
  - postgresql
  - redis
  - monitoring
annotations:
  category: Analytics
  licenses: Apache-2.0
dependencies:
  - name: postgresql
    version: "~12.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "~17.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: prometheus
    version: "~15.0.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  - name: grafana
    version: "~6.0.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled